In [1]:
import numpy as np
import pandas as pd
from PIL import Image
import os

In [2]:
import keras

In [3]:
keras.__version__

'2.11.0'

In [ ]:
df = pd.read_csv("images.csv")

In [5]:
images_path = "images_original"
files = os.listdir(images_path)

In [6]:
files_list = np.empty((len(files),), dtype='<U40')
for i in range(files_list.size):
    files_list[i] = files[i]

In [7]:
files_list

array(['d7ed1d64-2c65-427f-9ae4-eb4aaa3e2389.jpg',
       '5c1b7a77-1fa3-4af8-9722-cd38e45d89da.jpg',
       'b2e084c7-e3a0-4182-8671-b908544a7cf2.jpg', ...,
       'd4b0b957-5632-4df1-aba6-e562e2a84687.jpg',
       '89074ff2-ebfe-4790-892e-8513625a05b0.jpg',
       '0949e8e0-c807-4b6d-8453-80a05f1b733e.jpg'], dtype='<U40')

In [8]:
x_train = np.empty((files_list.size,), dtype=np.ndarray)
y_train = np.empty((files_list.size), dtype='<U40')

In [ ]:
index = 0
for element in files_list:
    splitted = element.split(".")
    print(splitted)
    if not df.empty and splitted[0] in df["image"].values:
        print(f"{round(index/files_list.size * 100,2)}%\n")
        result = df.loc[df["image"] == splitted[0]].iloc[0]["label"]
        img = Image.open(f"{images_path}/{element}")
        img = img.resize((32, 32))
        img = img.convert('L')
        img_array = np.array(img)
        flattened_img = img_array.flatten()
        x_train[index] = flattened_img
        y_train[index] = result
        index += 1
    else:
        print(f"No label found for image: {element}")

In [10]:
x_train

array([array([51, 54, 58, ..., 41, 39, 37], dtype=uint8),
       array([ 26,  28,  29, ...,  81,  92, 100], dtype=uint8),
       array([ 61,  65,  69, ..., 107, 115, 120], dtype=uint8), ..., None,
       None, None], dtype=object)

In [11]:
x_train.size

5762

In [12]:
index = [i for i in x_train if i is not None]

In [13]:
x_train = np.empty((len(index),), dtype=np.ndarray)
for i in range(x_train.size):
    x_train[i] = index[i]

In [14]:
x_train.size

5403

In [15]:
y_train

array(['Undershirt', 'Longsleeve', 'T-Shirt', ..., '', '', ''],
      dtype='<U40')

In [16]:
index = [i for i in y_train if i != '']

In [17]:
len(index)

5403

In [18]:
y_train = np.empty((len(index),), dtype=np.ndarray)
for i in range(y_train.size):
    y_train[i] = index[i]

In [19]:
y_train.size

5403

In [20]:
df["label"].unique()

array(['Not sure', 'T-Shirt', 'Shoes', 'Shorts', 'Shirt', 'Pants',
       'Skirt', 'Other', 'Top', 'Outwear', 'Dress', 'Body', 'Longsleeve',
       'Undershirt', 'Hat', 'Polo', 'Blouse', 'Hoodie', 'Skip', 'Blazer'],
      dtype=object)

In [21]:
np.save('x_train_save.npy', x_train)

In [22]:
x_train

array([array([51, 54, 58, ..., 41, 39, 37], dtype=uint8),
       array([ 26,  28,  29, ...,  81,  92, 100], dtype=uint8),
       array([ 61,  65,  69, ..., 107, 115, 120], dtype=uint8), ...,
       array([74, 76, 76, ..., 70, 66, 62], dtype=uint8),
       array([197, 200, 202, ..., 127, 126, 124], dtype=uint8),
       array([83, 87, 83, ..., 95, 95, 88], dtype=uint8)], dtype=object)

In [23]:
np.save('y_train_save.npy', y_train)