## Neural network for categorizing clothing pieces

In [1]:
import numpy as np
import pandas as pd
from PIL import Image
import os
import keras
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

### Load the training sets (x,y) from the saves

In [2]:
x = np.load("x_train_save.npy", allow_pickle=True)

In [3]:
y = np.load("y_train_save.npy", allow_pickle=True)

In [4]:
x.size, y.size

(5403, 5403)

In [5]:
x[0].shape

(1024,)

In [6]:
np.unique(y).size

20

### Splitting them for training and testing

In [7]:
x_train, x_test = np.array_split(x, 2)
y_train, y_test = np.array_split(y, 2)

In [8]:
x_train.shape, y_train.shape

((2702,), (2702,))

In [9]:
label_encoder = LabelEncoder()
y_train_encoded = label_encoder.fit_transform(y_train)
y_test_encoded = label_encoder.fit_transform(y_test)

In [10]:
y_train_encoded

array([19,  6, 17, ..., 18, 16,  5])

In [11]:
y_test_encoded

array([17, 11,  3, ...,  8, 19, 12])

In [12]:
x_train = np.array([np.array(x) for x in x_train])
x_test = np.array([np.array(x) for x in x_test])

In [13]:
x_train_normalized = x_train / 255.0
x_test_normalized = x_test / 255.0

In [14]:
x_train_normalized

array([[0.2       , 0.21176471, 0.22745098, ..., 0.16078431, 0.15294118,
        0.14509804],
       [0.10196078, 0.10980392, 0.11372549, ..., 0.31764706, 0.36078431,
        0.39215686],
       [0.23921569, 0.25490196, 0.27058824, ..., 0.41960784, 0.45098039,
        0.47058824],
       ...,
       [0.37254902, 0.39215686, 0.40784314, ..., 0.57647059, 0.5254902 ,
        0.50196078],
       [0.70196078, 0.67843137, 0.69411765, ..., 0.54117647, 0.55686275,
        0.56862745],
       [0.69803922, 0.74901961, 0.77647059, ..., 0.72941176, 0.72156863,
        0.72156863]])

In [15]:
model = keras.Sequential()
model.add(keras.layers.Dense(64, activation='relu', input_shape=(1024,)))
model.add(keras.layers.Dense(64, activation='relu'))
model.add(keras.layers.Dense(1, activation='softmax'))

In [16]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 64)                65600     
                                                                 
 dense_1 (Dense)             (None, 64)                4160      
                                                                 
 dense_2 (Dense)             (None, 1)                 65        
                                                                 
Total params: 69,825
Trainable params: 69,825
Non-trainable params: 0
_________________________________________________________________


In [17]:
model.compile(optimizer='adam',
              loss=keras.losses.CategoricalCrossentropy(),
              metrics=['accuracy'])


In [18]:
y_train_encoded.shape

(2702,)

In [19]:
model.fit(x_train_normalized, y_train_encoded,
          batch_size=128,
          epochs=40,
          validation_data=(x_test_normalized, y_test_encoded))

Epoch 1/40


2024-02-16 10:32:56.424134: W tensorflow/tsl/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz


22/22 [==============================] - 0s 7ms/step - loss: 0.0000e+00 - accuracy: 0.0041 - val_loss: 0.0000e+00 - val_accuracy: 0.0044
Epoch 2/40
22/22 [==============================] - 0s 3ms/step - loss: 0.0000e+00 - accuracy: 0.0041 - val_loss: 0.0000e+00 - val_accuracy: 0.0044
Epoch 3/40
22/22 [==============================] - 0s 3ms/step - loss: 0.0000e+00 - accuracy: 0.0041 - val_loss: 0.0000e+00 - val_accuracy: 0.0044
Epoch 4/40
22/22 [==============================] - 0s 3ms/step - loss: 0.0000e+00 - accuracy: 0.0041 - val_loss: 0.0000e+00 - val_accuracy: 0.0044
Epoch 5/40
22/22 [==============================] - 0s 3ms/step - loss: 0.0000e+00 - accuracy: 0.0041 - val_loss: 0.0000e+00 - val_accuracy: 0.0044
Epoch 6/40
22/22 [==============================] - 0s 3ms/step - loss: 0.0000e+00 - accuracy: 0.0041 - val_loss: 0.0000e+00 - val_accuracy: 0.0044
Epoch 7/40
22/22 [==============================] - 0s 3ms/step - loss: 0.0000e+00 - accuracy: 0.0041 - val_loss: 0.0000e+0

In [20]:
test_scores = model.evaluate(x_test_normalized, y_test_encoded)
print("Test loss:", test_scores[0])
print("Test accuracy:", test_scores[1])

85/85 [==============================] - 0s 565us/step - loss: 0.0000e+00 - accuracy: 0.0044
Test loss: 0.0
Test accuracy: 0.004442798905074596


In [21]:
test_scores

[0.0, 0.004442798905074596]